### ISSUE TITLE
Not quite sure how to use this...

### ISSUE THREAD

**Issue by JayMatthew** [gdiazderadaa/vc-schema.org#2]
I do not see any detailed instructions here for how to use this. I know how to to Schema inline in the code, but this application does not allow for that... right? or am I wrong? Could you make a video, or a detailed guide on how exactly this works?

**Comment by gdiazderadaa** [comment]
Hi @JayMatthew , I've updated the readme with some pictures that may be helpful. Any questions just let me know

**Comment by JayMatthew** [comment]
Okay, but how can you schema within the text boxes? Normally you do this
inline using code, which does not work. The plugin does not solve this
issue. There are typically multiple schema markups in blocks of text... how
does this work for that?
On May 2, 2016 9:44 AM, "Germán Díaz de Rada" <notifications@github.com>
wrote:

Hi @JayMatthew <https://github.com/JayMatthew> , I've updated the readme
with some pictures that may be helpful. Any questions just let me know

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/gdiazderadaa/vc-schema.org/issues/2#issuecomment-216254566>

**Comment by gdiazderadaa** [comment]
Can you please provide an example so that I am able to understand what your actual concern is?

**Comment by JayMatthew** [comment]
Send me an email and I will show you. I am not gonna put our stuff up on
here though.

*Owner - Jay Matthew Consulting*
*Cross-Industry Consulting, Marketing, Brand Development & Crisis
Management*
*Political / Nonprofit / Private Sector*
*562-896-1643*
*www.jaymatthew.org <http://www.jaymatthew.org>*

**Comment by JayMatthew** [comment]
Thanks for adding the photos, but that did not really help me with how to actually use the tool. I would like to see it action. I do not think you built this for the type of schema markup we are trying to do... but I can't be sure unless I actually see it working and being used the way you intend it. The screen caps are just showing me the forms I had already seen.

**Comment by Gillis86** [comment]
hi thank you for that
i've tried to edited something in my home page but the structured data testing tool doesnt show the microdata. Can you show us a concrete example about how use this extension?
Thank you again

**Comment by JayMatthew** [comment]
How could I accomplish the same kind of schema that is on jaymatthew.org
using your tool? I somehow got schema markup to work on my VC run site
manually... but cant replicate it on other sites. Could I use your tool to
accomplish this? If so, how do I get this level of information?

*Owner - Jay Matthew Consulting*
*Cross-Industry Consulting, Marketing, Brand Development & Crisis
Management*
*Political / Nonprofit / Private Sector*
*562-896-1643*
*www.jaymatthew.org <http://www.jaymatthew.org>*

**Comment by gdiazderadaa** [comment]
I will try to provide you both with an example in the next few days, but I can't say when it will be as I'm so overloaded right now. Apologies.

**Comment by Gillis86** [comment]
ok thank you very much
i have one more question: i put in my theme folder only the files:
vc-schema.org.php
vc-column.php
vc-column_text.php
vc_row-php
is it ok?

**Comment by gdiazderadaa** [comment]
I've amended the Readme to avoid confussions. When you download the plugin just take the file vc.shema.org.php and the folder vc_templates and put them into your current wp theme folder.
